spring.application.name=grasp

server.port=8080
server.error.include-message=always

spring.datasource.url=jdbc:postgresql://localhost:5432/grasp_blog_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# use update for dev's auto-table creation, 'validate' for prod
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# disable cache during development so we can see html changes immediately
spring.thymeleaf.cache=false
